### 3. 유저회원가입 API
POST http://localhost:3001/user/sign-up
Content-Type: application/json

{
    "email": "kimdoha2@gmail.com",
    "password": "kimdoha123"
}


### 4. 유저로그인 API
POST http://localhost:3001/user/sign-in
Content-Type: application/json

{
    "email": "kimdoha2@gmail.com",
    "password": "kimdoha123"
}