### 3. 유저회원가입 API
POST http://localhost:3001/user/sign-up
Content-Type: application/json

{
    "email": "kimdoha@gmail.com",
    "password": "kimdoha123"
}


### 4. 유저로그인 API
POST http://localhost:3001/user/sign-in
Content-Type: application/json

{
    "email": "kimdoha@gmail.com",
    "password": "kimdoha123"
}


### 유저 정보 조회
GET http://localhost:3001/user/profile-info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE2IiwiZW1haWwiOiJraW1kb2hhQGdtYWlsLmNvbSIsImlhdCI6MTY1NzQ2NTY5OSwiZXhwIjoxNjU3NDY5Mjk5fQ.TmlQygpVSZH4uWPBftshRrsLQrXqo8FHhzQYhU2q_6c


### 유저 위치 수정
PATCH http://localhost:3001/user/location
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE2IiwiZW1haWwiOiJraW1kb2hhQGdtYWlsLmNvbSIsImlhdCI6MTY1NzU1MTc4MiwiZXhwIjoxNjU3NTU1MzgyfQ.s1JQYpdwyWP-HzTWNyl108wgy86Wr1uXafF73nmwRIc
Content-Type: application/json

{
    "location_x" : 12.999,
    "location_y": 12.999
}
