### 3. 유저회원가입 API
POST http://localhost:3001/user/sign-up
Content-Type: application/json

{
    "email": "kimdoha@gmail.com",
    "password": "kimdoha123"
}


### 4. 유저로그인 API
POST http://localhost:3001/user/sign-in
Content-Type: application/json

{
    "email": "kimdoha@gmail.com",
    "password": "kimdoha123"
}


### 유저 정보 조회
GET http://localhost:3001/user/profile-info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE2IiwiZW1haWwiOiJraW1kb2hhQGdtYWlsLmNvbSIsImlhdCI6MTY1NzE5MzQyMCwiZXhwIjoxNjU3MTk3MDIwfQ.CG89Bsb_BMYA2U7Zavj0CsyU2q5xiwARcpYUfwsD1KI
