### 1. 인증 번호 이메일 발송 API
POST http://localhost:3001/auth
Content-Type: application/json

{
    "email": "kimdoha@gmail.com"
}

### 2. 인증 확인 API
GET http://localhost:3001/auth/verification?email=kimdoha@gmail.com&value=pCp444

